# Generated by Django 4.2.7 on 2023-11-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=255, null=True)),
                ('precover', models.ImageField(blank=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, upload_to='video/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=255, null=True)),
                ('precover', models.ImageField(blank=True, upload_to='images/')),
                ('videos', models.FileField(blank=True, upload_to='video/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
